language: python

python:
- "3.6"

install: 
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database try_viserys;' -U postgres
  
script: 
  - coverage run --source=app -m py.test && coverage report

after_success:
  - coveralls